### ISSUE TITLE
Help! Markbot is not letting me complete my project!

### ISSUE THREAD

**Issue by kyramari** [acgd-webdev-1/content-semantics#2]
When checking my work using Markbot, it says I have to indent the last line (which has nothing on it). So I make the indents, but when I save the file, it creates another new line at the bottom. When I check it in Markbot, it than says to indent the last line, which was just created when I saved the file. So this goes on and on, because a new line is created when I save each time, and Markbot wants me to indent it. 
I hope I explained that ok.

What should I do?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Please commit and sync your code so I can look at it.

**Comment by kyramari** [comment]
oh ya. I forgot that. What file do I attach though?

**Comment by kyramari** [comment]
I think I synced it now.

**Comment by thomasjbradley** [comment]
I think it's because of the error in Markbot, it wasn't working properly on some peoples computers.

When I look at your code, there are a bunch of validation errors, here's a screenshot:
![screen shot 2016-01-26 at 2 51 27 pm](https://cloud.githubusercontent.com/assets/105192/12592868/504ff4a6-c43c-11e5-96bb-1e7364bf2609.png)

Those are probably causing the problem.

Download the new version, I just sent around a message on Canvas, but here's the link:
https://www.dropbox.com/s/55a7uzj6uy3uhx8/Markbot.dmg?dl=1

**Comment by kyramari** [comment]
Ya I actually did that. But those still aren't the same errors that I have.

**Comment by thomasjbradley** [comment]
Send me a screenshot of Markbot, please.

**Comment by kyramari** [comment]
<img width="803" alt="screen shot 2016-01-26 at 2 56 11 pm" src="https://cloud.githubusercontent.com/assets/16653506/12593025/f9dbcf2c-c43c-11e5-80cc-f35e97bf17c2.png">

**Comment by kyramari** [comment]
Yours say to indent on line 65 and 67 but I only have stuff up to line 60.

**Comment by thomasjbradley** [comment]
Do the validation errors first—they are likely the cause of the indentation problems.

**Comment by kyramari** [comment]
Ok I'll try that.
