### ISSUE TITLE
Indentation issues 

### ISSUE THREAD

**Issue by DoctorDiLauro** [acgd-webdev-1/content-semantics#4]
Hey Thomas, just got the new Markbot and cleaned up all my validation errors, but I'm still getting a bunch of indentation errors.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Commit and sync it to GitHub so I can have a look at your code please.

**Comment by DoctorDiLauro** [comment]
Hey Thomas, sorry for the late reply. Everything should be all up to date on GitHub

**Comment by thomasjbradley** [comment]
There's still nothing there, the `index.html` file isn't visible, did you sync?

**Comment by DoctorDiLauro** [comment]
Ah right....sorry, was only hitting commit. Me hitting sync would probably help with the syncing process. Alright, should be up now.

**Comment by thomasjbradley** [comment]
Okay, yeah, I see. Many people have been running into this problem because Markbot isn't being specific enough with its error messages.

[**Download the new version here.**](https://www.dropbox.com/s/55a7uzj6uy3uhx8/Markbot.dmg?dl=1)

The problem is the `<dt>` and `<dd>` tags, they should be on their own lines, like below.
(The new Markbot will point that out to you directly.)

```html
    <dl>
      <dt>Energy:</dt>
      <dd><data value="180">180 kJ</data></dd>
      <dt>Carbohydrates:</dt>
      <dd><data value="9.96">9.96 g</data></dd>
      <dt>Fat:</dt>
      <dd><data value="0.18">0.18 g</data></dd>
      <dt>Protein:</dt>
      <dd><data value="1.6">1.6 g</data></dd>
    </dl>
```

*The rest of your indentation looks immaculate!*

**Comment by DoctorDiLauro** [comment]
Ah okay, I'll download the new one and fix up the errors. Thanks!
